platformatic/meraki

src/main/generate.mjs
Without this change, Platformatic DB won't apply the migrations.
=> Add logger and post-install actions

electron-builder.yml, package-lock.json, package.json, src/main/index.mjs, src/main/menu.mjs, src/main/updater.mjs
Fixes: https://github.com/platformatic/meraki/issues/75
The us is very basic, can be improved in different PRs. 
Also added electron logger
@tonysnowboardunderthebridge or @leorossi can you please test it on OSx? To test, just change the version on `package.json` to one which is LESS then latest (e.g. `0.0.1`) and then launch the app. 
The `update check` is currently under the `help` menu
=> Automatic updater [DON'T MERGE]

package-lock.json, package.json, src/renderer/src/components/templates/SelectTemplate.jsx
=> 19 add template count to filters on select template

src/main/index.mjs, src/renderer/index.html
=> show the version in the window title

package-lock.json, package.json, src/renderer/src/components/plugins/Plugin.jsx, src/renderer/src/components/plugins/PluginDetail.jsx, src/renderer/src/components/plugins/PluginDetail.module.css, src/renderer/src/components/plugins/PluginEnvVarsForm.jsx, src/renderer/src/components/plugins/SelectPlugin.jsx, src/renderer/src/components/services/EditService.jsx, src/renderer/src/components/steps/ConfigureApplication.jsx, src/renderer/src/components/steps/CreateApplication.jsx, src/renderer/src/components/steps/GeneratingApplication.jsx, src/renderer/src/components/steps/GeneratingApplication.module.css, src/renderer/src/components/steps/PrepareFolder.jsx, src/renderer/src/components/steps/configure-services/ConfigureService.jsx, src/renderer/src/components/templates/SelectTemplate.jsx, src/renderer/src/components/templates/Template.jsx, src/renderer/src/components/templates/TemplateDetail.jsx, src/renderer/src/components/templates/TemplateDetail.module.css, src/renderer/src/components/templates/TemplateEnvVarsForm.jsx, src/renderer/src/components/ui/EditableTitle.jsx, src/renderer/src/layout/Header.jsx, src/renderer/src/styles/CommonStyles.module.css
Here we have the scaffholding for Plugins and Templates details
=> 15 add missing details for template and plugins

package-lock.json, package.json, src/renderer/src/components/plugins/Plugin.jsx, src/renderer/src/components/plugins/PluginDetail.jsx, src/renderer/src/components/plugins/PluginEnvVarsForm.jsx, src/renderer/src/components/plugins/SelectPlugin.jsx, src/renderer/src/components/plugins/SelectPlugin.module.css, src/renderer/src/components/services/EditService.jsx, src/renderer/src/components/services/RemoveService.jsx, src/renderer/src/components/steps/ConfigureApplication.jsx, src/renderer/src/components/steps/CreateApplication.jsx, src/renderer/src/components/steps/GeneratingApplication.jsx, src/renderer/src/components/steps/PrepareFolder.jsx, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/steps/configure-services/ConfigureServices.jsx, src/renderer/src/components/steps/configure-services/ConfigureServices.module.css, src/renderer/src/components/templates/SelectTemplate.jsx, src/renderer/src/components/templates/SelectTemplate.module.css, src/renderer/src/components/templates/Template.jsx, src/renderer/src/components/templates/TemplateDetail.jsx, src/renderer/src/components/ui/EditableTitle.jsx
here the PR for meraki regarding the update of ui-components
=> Bugfix/updating UI component with breaking changes

src/main/lib/import-or-local.mjs
fixes: https://github.com/platformatic/meraki/issues/148
=> Don't show warn as errors

src/renderer/src/components/plugins/Plugin.jsx, src/renderer/src/components/plugins/SelectPlugin.jsx, src/renderer/src/components/plugins/SelectPlugin.module.css, src/renderer/src/components/templates/SelectTemplate.jsx, src/renderer/src/components/templates/SelectTemplate.module.css, src/renderer/src/components/templates/Template.jsx, src/renderer/src/ui-constants.js
=> 170 template names are not readable by default on mac os x

src/main/index.mjs
Fixes: https://github.com/platformatic/meraki/issues/177
Still needs to be tested on Mac
=> Windows fix for open template with deep link

src/main/client.mjs
Fixes: https://github.com/platformatic/meraki/issues/77
=> Manage networking errors and show a dialog box

package-lock.json, package.json, src/renderer/src/App.css
Hi @marcopiraccini, with this one, I correct the misalignment between buttons
=> fix: updating app for having aligned buttons

src/renderer/src/components/steps/CreateApplication.jsx
here the PR for resolve https://github.com/platformatic/meraki/issues/219
=> fix: updating for name with dots

src/renderer/src/components/services/Service.jsx, src/renderer/src/components/services/Service.module.css, src/renderer/src/components/shaped-components/AddPlugin.module.css, src/renderer/src/components/shaped-components/AddTemplate.module.css, src/renderer/src/components/shaped-components/PlatformaticRuntimeButton.module.css, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/steps/compose-application/GridElement.jsx, src/renderer/src/components/steps/compose-application/GridElement.module.css, src/renderer/src/components/steps/compose-application/GridView.jsx, src/renderer/src/components/steps/compose-application/NormalView.jsx
final updates with also some changes on the app when we have more than 4 templates selected
=> fix: updating css for prevent problems on alignement between blocks

src/renderer/src/components/steps/CreateApplication.jsx, src/renderer/src/styles/Typography.module.css
first step changes and upgrade!
=> fix: updating first step changes

src/renderer/src/components/application/EditApplicationName.jsx, src/renderer/src/components/application/EditApplicationName.module.css, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/ui/EditableTitle.jsx
fix: adapting Editable Title to handling the name of the application
=> Meraki Review: editing application name as modal

package-lock.json, package.json, src/renderer/src/components/application/EditApplicationName.jsx, src/renderer/src/components/plugins/Plugin.jsx, src/renderer/src/components/plugins/Plugin.module.css, src/renderer/src/components/plugins/SelectPlugin.module.css, src/renderer/src/components/services/EditService.jsx, src/renderer/src/components/steps/ConfigureApplication.jsx, src/renderer/src/components/steps/CreateApplication.jsx, src/renderer/src/components/steps/PrepareFolder.jsx, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/steps/configure-services/ConfigureServices.jsx, src/renderer/src/components/templates/SelectTemplate.module.css, src/renderer/src/components/templates/Template.jsx, src/renderer/src/components/templates/Template.module.css, src/renderer/src/styles/ModalStyles.module.css
others fixes from notion documents
=> 251 meraki review notion page step 2 buttons and other changes

src/renderer/src/components/shaped-components/AddPlugin.jsx, src/renderer/src/components/shaped-components/AddPlugin.module.css, src/renderer/src/components/shaped-components/AddService.jsx, src/renderer/src/components/shaped-components/AddTemplate.jsx, src/renderer/src/components/shaped-components/AddTemplate.module.css, src/renderer/src/components/shaped-components/BrickPath.jsx, src/renderer/src/components/shaped-components/ChangeTemplate.jsx, src/renderer/src/components/shaped-components/ChangeTemplate.module.css, src/renderer/src/components/shaped-components/PluginButton.jsx, src/renderer/src/components/shaped-components/PluginButton.module.css
adding some hover effect css for components on the Compose Application step
=> fix: updating puzzle components with hover effect

package-lock.json, package.json, src/main/index.mjs, src/preload/index.js, src/renderer/src/api.js, src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/applications/recent/RecentApplications.module.css, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/applications/recent/Row.module.css, src/renderer/src/components/applications/recent/Table.jsx, src/renderer/src/components/applications/recent/Table.module.css, src/renderer/src/components/applications/recent/TopContent.jsx, src/renderer/src/components/applications/recent/TopContent.module.css, src/renderer/src/components/component.animation.css, src/renderer/src/components/ui/SideBar.jsx, src/renderer/src/components/ui/SideBar.module.css, src/renderer/src/components/welcome/Welcome.jsx, src/renderer/src/ui-constants.js, src/renderer/src/utilitySorting.js
Hi @leorossi 
here the PR for having the Recent Apps working Page
screenshot of the final result
=> 273 recent apps UI

package-lock.json, package.json, src/renderer/src/App.jsx, src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/ApplicationContainer.module.css, src/renderer/src/components/HomeContainer.jsx, src/renderer/src/components/HomeContainer.module.css, src/renderer/src/components/application/environment-variables/EnvironmentVariables.jsx, src/renderer/src/components/application/environment-variables/EnvironmentVariables.module.css, src/renderer/src/components/application/metrics/Metrics.jsx, src/renderer/src/components/application/metrics/Metrics.module.css, src/renderer/src/components/application/overview/Overview.jsx, src/renderer/src/components/application/overview/Overview.module.css, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/all/Row.module.css, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/applications/recent/Row.module.css, src/renderer/src/components/applications/recent/TopContent.module.css, src/renderer/src/components/ui/SideBar.module.css, src/renderer/src/layout/Header.jsx, src/renderer/src/layout/Header.module.css, src/renderer/src/layout/Navigation.jsx, src/renderer/src/layout/Navigation.module.css, src/renderer/src/main.jsx, src/renderer/src/ui-constants.js, src/renderer/src/useStackablesStore.js
here the PR for all the changes on sidebar and on navigation bar
=> 278 app detail UI   sidebar and navigation bar

src/renderer/src/components/application/DeleteApplication.jsx, src/renderer/src/components/application/import/ImportApplicationFlow.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/all/TableAll.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/applications/recent/TableRecent.jsx
I've added the modals and the handler to let the user delete the applications
=> feat: adding handling for delete application

src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/application-logs/ApplicationLogs.module.css, src/renderer/src/components/application/application-logs/Log.jsx, src/renderer/src/components/application/application-logs/Log.module.css, src/renderer/src/styles/CommonStyles.module.css, src/renderer/src/ui-constants.js
I added some mock logs, and I prepared this PR, with also the scroll behavior
I will record a loom once that I finish this page
- before completing the ui, I need to update on ui-components.
- use the update of ui-components and add the log Filter Level (next PR)
=> 294 app detail UI   logs

src/main/index.mjs, src/renderer/src/App.jsx, src/renderer/src/api.js, src/renderer/src/components/Wizard.jsx, src/renderer/src/components/application/create/CreateApplicationFlow.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/steps/GeneratingApplication.jsx
handling differently the creation of the app if we use wizard with old version or new version
=> fix: fixup

src/main/generate.mjs
Otherwise we won't be able to interact with running runtimes.
=> Enable management APIs in generated apps

src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/overview/Overview.jsx, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/OverviewSection.module.css, src/renderer/src/components/application/overview/ServiceElement.jsx, src/renderer/src/components/application/overview/ServiceElement.module.css, src/renderer/src/components/application/overview/ServicesSection.jsx, src/renderer/src/components/application/overview/ServicesSection.module.css, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/application/overview/TopContent.module.css, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/all/Row.module.css, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/applications/recent/Row.module.css, src/renderer/src/components/ui/ApplicationStatusPills.jsx, src/renderer/src/components/ui/ApplicationStatusPills.module.css, src/renderer/src/styles/Typography.module.css, src/renderer/src/ui-constants.js
structure of the following page on PR:
=> fix: adding first part of the structure

src/renderer/src/App.jsx, src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/application-logs/Log.jsx, src/renderer/src/components/application/application-logs/Log.module.css, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/all/Row.module.css, src/renderer/src/components/applications/all/TableAll.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/applications/recent/Row.module.css
- update Start and Stop button
- update logs
https://www.loom.com/share/3c1c69467e5448a8b9056e6315d7bb1c
https://www.loom.com/share/2277560a4e81478ea9db499596dd098c
https://www.loom.com/share/d616022de8a34c979cc9040fecdf7a40
=> fix: adding logic for handling stop and start button and logs

src/preload/index.js, src/renderer/src/api.js, src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/OverviewSection.module.css
implemented (loom below)
https://www.loom.com/share/ed8143ac221b433eab2a0fbb8e443e83
=> Download all logs

src/main/index.mjs, src/main/lib/applications.mjs, src/main/lib/inspect-app.mjs, src/preload/index.js, test/main/applications.test.mjs
This is to show the application structure (services, etc) in the application detail.
=> Open application API

src/renderer/src/App.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/useStackablesStore.js, src/renderer/src/utilityDetails.js
fixed: 
- List applications is now updated when create or import app (moved the handling inside store)
- Last Started and Last Update date format
- When Create New App is clicked after a successfull creation of an app, the state is clean now
=> List App Not updated when imported or created app

src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/application/edit/DiscardChanges.jsx, src/renderer/src/components/application/edit/EditApplicationFlow.jsx, src/renderer/src/components/application/edit/EditApplicationFlow.module.css, src/renderer/src/components/application/edit/HeaderEditApplicationFlow.jsx, src/renderer/src/components/application/edit/HeaderEditApplicationFlow.module.css, src/renderer/src/components/application/overview/Overview.jsx, src/renderer/src/components/application/overview/ServicesSection.jsx, src/renderer/src/components/wizard/EditWizard.jsx, src/renderer/src/components/wizard/EditWizard.module.css, src/renderer/src/useStackablesStore.js, src/renderer/src/utils.js, test/renderer/utils.test.mjs
in the following PR you will find: 
- a function (with the test ) for convert the response for open-app endpoint to populate the store for Edit Application on the Wizard
- a new component EditWizard that will be used for the Edid Application Flow
- adding new modals for the flow on UI
=> 277 edit app UI

src/renderer/src/components/services/NameService.jsx, src/renderer/src/components/shaped-components/ChangeTemplate.jsx, src/renderer/src/components/shaped-components/ChangeTemplate.module.css, src/renderer/src/components/steps/compose-application/GridElement.jsx, src/renderer/src/components/steps/compose-application/NormalView.jsx, src/renderer/src/components/template-and-plugins/TemplateAndPluginHandler.jsx, src/renderer/src/useStackablesStore.js, src/renderer/src/utils.js, test/renderer/utils.test.mjs
in this pr:
- handling the change template with disabled attribute and also the naming of the service
=> edit-app-ui-2

src/renderer/src/App.jsx, src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/application/application-logs/LogFilterSelector.jsx, src/renderer/src/components/application/application-logs/LogFilterSelector.module.css, src/renderer/src/components/application/create/CreateApplicationFlow.jsx, src/renderer/src/components/application/create/DiscardCreate.jsx, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/steps/compose-application/ComposeApplication.module.css, src/renderer/src/components/steps/compose-application/GridElement.jsx, src/renderer/src/components/steps/configure-services/ConfigureServices.jsx, src/renderer/src/components/wizard/EditWizard.jsx, src/renderer/src/useStackablesStore.js, src/renderer/src/utils.js, test/renderer/utils.test.mjs
in this PR I will handling the case of 
- adding a new service to an existing application with/without a plugin
and the result is the following
https://github.com/platformatic/meraki/assets/25035977/ad218c59-3719-446e-8536-6679cbe74103
=> fix: updating handling of a new service with the old one

test/main/applications.test.mjs
=> fix: updating test

package-lock.json, package.json, src/renderer/src/components/application/metrics/ColorSet0.module.css, src/renderer/src/components/application/metrics/ColorSet1.module.css, src/renderer/src/components/application/metrics/LineChart.jsx, src/renderer/src/components/application/metrics/LineChart.module.css, src/renderer/src/components/application/metrics/Metrics.jsx
time-shifting metrics in line charts. This is with random data, not real metrics (yet)
Demo
[see: 
https://www.loom.com/share/8674515d646f4af0a8b27ad76ec8cf9d?sid=c2dfdf0c-4689-4d69-86c9-16e451b20094](https://www.loom.com/share/e565990bdbbe44cfbe838b96d59bbfd2)
=> Line charts (with random data)

package-lock.json, package.json, src/renderer/src/components/screens/ErrorComponent.jsx, src/renderer/src/components/screens/ErrorComponent.module.css
here the update for the error component
=> fix: error component

src/renderer/src/App.jsx, src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/application-logs/ApplicationLogs.module.css, src/renderer/src/components/application/application-logs/LogFilterSelector.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/ui-constants.js
adding the fixing for filtering logs
=> Filtering logs

package-lock.json, package.json, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/screens/ErrorComponent.jsx
=> feat: using new tooltip

src/main/lib/logs.mjs, test/main/logs.test.mjs
Missing unit tests and some small fixes in logs API
=> Log test fixes

src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/ServiceElement.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/applications/recent/Row.jsx
HI @leorossi 
- fix: correct behavior of stop on application page not reflected on list pages
- AlertIcon on the list should be displayed only if the platformaticVersion is present
- Same behavior on the overview page
- Typescript and Javascript icon determined by env variable
=> bugfix on different pages

src/renderer/src/components/application/metrics/StackedBarsChart.jsx, src/renderer/src/components/application/metrics/charts.module.css
=> P50 on latency metrics

src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/metrics/Metrics.jsx, src/renderer/src/components/application/metrics/Metrics.module.css, src/renderer/src/components/application/overview/Overview.jsx, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/ServicesSection.jsx, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/useStackablesStore.js
with this PR the handling of the status of an applicaiton is correct and reflected on all the pages that need that
=> fix: updating handling of status

src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/overview/Overview.jsx, src/renderer/src/components/templates/SelectTemplate.jsx, src/renderer/src/ui-constants.js
small PR for handling a refresh on applicaiton detail page
=> fix: updating stuff

src/main/lib/logs.mjs
(instead of concatenating the streams as before)
=> Uses the new API in plt1.30.0 to get all logs in one stream

src/renderer/src/App.jsx, src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/useStackablesStore.js
I added the automatic restart for each application
=> feat: adding automatic restart

src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/all/TableAll.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/applications/recent/TableRecent.jsx
handling the restart button on the list and on the application detail page
=> fix: adding restart button logic

src/main/generate.mjs
=> call runtime.loadFromDir() before update

src/main/lib/applications.mjs, src/renderer/src/api.js, src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/environment-variables/DisplayEnvironmentVariables.jsx, src/renderer/src/components/application/metrics/Metrics.jsx, src/renderer/src/components/application/overview/Overview.jsx, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/ServicesSection.jsx, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/ui-constants.js, src/renderer/src/useStackablesStore.js
updated the store for handling better change of state and then also url and latest platformatic version on the details
=> fix: moving state of applications selected inside store

src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/application/DeleteApplication.jsx, src/renderer/src/components/application/EditApplicationName.jsx, src/renderer/src/components/application/edit/EditApplicationFlow.jsx, src/renderer/src/components/application/edit/StopApplicationToEdit.jsx, src/renderer/src/components/application/import/ImportApplicationFlow.jsx, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/ServiceElement.jsx, src/renderer/src/components/application/overview/ServiceElement.module.css, src/renderer/src/components/application/overview/ServicesSection.jsx, src/renderer/src/components/application/overview/ServicesSection.module.css, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/application/overview/TopContent.module.css, src/renderer/src/components/services/EditService.jsx, src/renderer/src/components/services/RemoveService.jsx, src/renderer/src/components/steps/GeneratingApplication.jsx
adding the handling for Edit Application (Modal that block the user, giving him/her choice to stop the application or close the edit modal).
=> 435 modal to stop application when edit it

src/renderer/src/components/application/metrics/LineChart.jsx, src/renderer/src/components/application/metrics/Metrics.jsx, src/renderer/src/components/application/metrics/Metrics.module.css, src/renderer/src/components/application/metrics/StackedBarsChart.jsx, src/renderer/src/components/application/metrics/charts.module.css
some updates for the ui disalignment from Figma to Meraki
=> Bugfix/metrics UI alignment figma

src/main/index.mjs, src/main/template-id.mjs, src/preload/index.js, src/renderer/src/App.jsx, src/renderer/src/api.js, src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/HomeContainer.jsx, src/renderer/src/components/application/overview/ServiceElement.jsx, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/screens/ErrorComponent.jsx, src/renderer/src/components/steps/CreateApplication.jsx, src/renderer/src/components/welcome/Welcome.jsx, src/renderer/src/components/wizard/EditWizard.jsx, src/renderer/src/useStackablesStore.js
Hi @marcopiraccini, 
completed, now Use Template works:
- on Welcome Page open the modal for create new app
- on List Page, open the modal for create a new app
- on Application Detail, open the modal for edit the application with the template selected added to the templates of the current application
=> 255 usetemplate should open an opened app in edit mode adding the template

src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/all/TableAll.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx
@marcopiraccini typo on ui for field lastUpdated
=> fix: typo lastUpdated

package-lock.json, package.json, src/renderer/src/components/Scalar.jsx, src/renderer/src/components/application/overview/Overview.jsx, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/ServicesSection.jsx
https://github.com/platformatic/meraki/assets/6176314/5d79ad1c-44b5-4bc3-b168-fc97170a59af
looking forward to everyones feedback!
some things that are left:
- theme polish
- fix height issue
- hiding of the baseUrl
- customize the client libraries
- right align the api client modal
=> feat: initial scalar integration

src/renderer/src/components/application/application-logs/ApplicationLogs.jsx
Check on previous logs is hidden when the application is stopped
=> fix: show button check previous logs only if application is started

src/renderer/src/components/steps/EditConfigureApplication.jsx
as titled
Resolve https://github.com/platformatic/meraki/issues/475
=> fix: removing Git Create Repo from Edit Application Flow

src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/recent/Row.jsx
this will resolve https://github.com/platformatic/meraki/issues/472
=> fix: restart disabled when app stopped

src/preload/index.js, src/renderer/src/components/application/metrics/LineChart.jsx, src/renderer/src/components/application/metrics/StackedBarsChart.jsx
Fixes: https://github.com/platformatic/meraki/issues/477
Also, unregister the listener for metrcis on closing.
=> Tooltip not cut when chart width is reached

package-lock.json, package.json, src/main/index.mjs, src/main/lib/runtime-proxy.mjs, src/preload/index.js, src/renderer/src/api.js, src/renderer/src/components/application/overview/ServicesSection.jsx, test/fixtures/runtime/services/service-1/platformatic.json, test/main/runtime-proxy.test.mjs
This exports the API to start the runtime proxy (the start returns the URL of the proxy) and to stop, under the assumption that it's open one proxy at a given time (i.e. no multiple proxies started in parallel are supported).
=> Runtime services proxy for Scalar

src/preload/index.js, src/renderer/src/api.js, src/renderer/src/components/application/DeleteApplication.jsx, src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/metrics/Metrics.module.css, src/renderer/src/components/steps/GeneratingApplication.jsx, src/renderer/src/components/steps/PrepareFolder.jsx, src/renderer/src/components/steps/UpdatingApplication.jsx
updates for removeListeners from electron when using useEffect
Resolve https://github.com/platformatic/meraki/issues/476
=> 476 ee leak

src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/application/application-logs/Log.jsx, src/renderer/src/components/application/application-logs/Log.module.css, src/renderer/src/components/plugins/Plugin.jsx, src/renderer/src/components/templates/SelectTemplate.jsx, src/renderer/src/components/templates/Template.jsx, src/renderer/src/components/welcome/Welcome.jsx, src/renderer/src/styles/CommonStyles.module.css, src/renderer/src/utilityDetails.js
first update of logs for fixing the line appereance of both (Pretty/Raw)
=> fix: updating logs

src/main/lib/applications.mjs
Fixes: https://github.com/platformatic/meraki/issues/470
=> Disable stdout logs for started apps

src/renderer/src/api.js, src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/hooks/useOnScreen.jsx
here PR for last part of the logs....
- show Previous Logs only if the api returns true
- reaching the bottom of the page will continue performing a tail
=> 478 fix logs 3

package-lock.json, package.json, src/main/lib/applications.mjs, src/main/lib/run-npm.mjs
See: https://github.com/netlify/build/issues/387
=> Fix for start runtime in windows

package-lock.json, package.json, src/renderer/src/components/application/application-logs/Log.jsx, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/screens/ErrorComponent.jsx, src/renderer/src/components/screens/ErrorComponent.module.css, src/renderer/src/components/shaped-components/PlatformaticRuntimeButton.jsx, src/renderer/src/components/shaped-components/PlatformaticRuntimeButton.module.css, src/renderer/src/components/ui/MerakiIcon.jsx, src/renderer/src/components/ui/MerakiIcon.module.css
Here the new tooltips, depends from https://github.com/platformatic/ui-components/pull/284
=> fix: updating tooltip

src/main/menu.mjs
copy and paste for the app
Resolve https://github.com/platformatic/meraki/issues/286
=> fix: support copy and paste

src/renderer/src/App.jsx, src/renderer/src/layout/Header.jsx, src/renderer/src/layout/Header.module.css
This reverts commit ad865033c3ea4c991a8a2e827d69eeb0fb4392b2.
=> Revert "Removed ff for v1.0"

src/renderer/src/components/plugins/ViewAll.jsx, src/renderer/src/components/services/NameService.jsx, src/renderer/src/components/shaped-components/PluginButton.jsx, src/renderer/src/components/shaped-components/PluginButton.module.css, src/renderer/src/components/ui/EditableTitle.jsx
adding small changes on ui during the step of wizard "Compose application"
=> fix: updating small changes for the ui

src/renderer/src/components/application/create/HeaderCreateApplicationFlow.module.css, src/renderer/src/components/application/edit/HeaderEditApplicationFlow.module.css, src/renderer/src/components/application/overview/Overview.jsx, src/renderer/src/components/application/overview/Overview.module.css, src/renderer/src/components/application/overview/ServicesSection.module.css, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/steps/compose-application/ComposeApplication.module.css, src/renderer/src/components/ui/SideBar.module.css
this resolve https://github.com/platformatic/meraki/issues/458
=> 458 meraki testing remaining points

src/renderer/src/components/application/metrics/StackedBarsChart.jsx, src/renderer/src/components/application/metrics/charts.module.css
=> update style of metrics

package-lock.json, package.json, src/main/index.mjs, src/main/menu.mjs, src/renderer/src/App.css, src/renderer/src/components/ApplicationContainer.jsx, src/renderer/src/components/HomeContainer.jsx, src/renderer/src/components/application/environment-variables/EnvironmentVariables.jsx, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/ServiceElement.jsx, src/renderer/src/components/application/overview/ServiceElement.module.css, src/renderer/src/components/applications/all/Row.module.css, src/renderer/src/components/applications/all/TableAll.module.css, src/renderer/src/components/applications/recent/Row.module.css, src/renderer/src/components/screens/ErrorComponent.jsx, src/renderer/src/components/ui/ApplicationStatusPills.jsx, src/renderer/src/components/ui/ApplicationStatusPills.module.css, src/renderer/src/components/ui/SideBar.module.css, src/renderer/src/styles/CommonStyles.module.css
this will resolve some small fixes and some adjusment required by @Fmusso94 on meraki testing
resolve https://github.com/platformatic/meraki/issues/516
resolve https://github.com/platformatic/meraki/issues/514
=> 516 small UI fixes on meraki components

src/main/index.mjs, src/main/menu.mjs
supporting full screen support
=> fix: adding fullscreen support and start with 1440

src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/application-logs/Log.jsx, src/renderer/src/components/application/environment-variables/EnvironmentVariables.jsx, src/renderer/src/components/application/metrics/LineChart.jsx, src/renderer/src/components/application/metrics/Metrics.jsx, src/renderer/src/components/application/metrics/StackedBarsChart.jsx, src/renderer/src/components/application/overview/Overview.module.css, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/ServiceElement.jsx, src/renderer/src/components/application/overview/ServicesSection.jsx, src/renderer/src/components/application/overview/ServicesSection.module.css, src/renderer/src/components/application/overview/TopContent.jsx, src/renderer/src/components/applications/all/AllApplications.module.css, src/renderer/src/components/applications/all/Row.jsx, src/renderer/src/components/applications/all/Row.module.css, src/renderer/src/components/applications/all/TableAll.module.css, src/renderer/src/components/applications/all/TopContent.jsx, src/renderer/src/components/applications/recent/RecentApplications.module.css, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/applications/recent/Row.module.css, src/renderer/src/components/applications/recent/TableRecent.module.css, src/renderer/src/components/applications/recent/TopContent.jsx, src/renderer/src/components/steps/CreateApplication.jsx, src/renderer/src/components/steps/CreateApplication.module.css, src/renderer/src/styles/CommonStyles.module.css, src/renderer/src/styles/Typography.module.css
latest changes requested by @Fmusso94 on meraki-testing
=> Features/small fixes UI 2

src/renderer/src/App.jsx, src/renderer/src/layout/Header.jsx, src/renderer/src/layout/Header.module.css
This will be merged before v1.0 to enable the new Meraki to all users.
=> Remove FF for v1.0

package-lock.json, package.json, src/renderer/src/components/application/application-logs/ApplicationLogs.jsx, src/renderer/src/components/application/application-logs/ApplicationLogs.module.css, src/renderer/src/components/application/metrics/Metrics.jsx, src/renderer/src/components/application/metrics/Metrics.module.css, src/renderer/src/hooks/useOnScreen.jsx, src/renderer/src/styles/CommonStyles.module.css
fix: updating screen with the desired images
Resolve https://github.com/platformatic/meraki/issues/520
=> 520-meraki-update-metrics-logs-screen-no-data-scenario

src/renderer/src/components/steps/GeneratingApplication.module.css, src/renderer/src/components/steps/PrepareFolder.module.css, src/renderer/src/components/steps/UpdatingApplication.jsx, src/renderer/src/components/steps/UpdatingApplication.module.css
=> fix: updating css with proper padding

src/renderer/src/components/application/application-logs/ApplicationLogs.module.css
=> bottom logs container disalignment

src/renderer/src/components/plugins/PluginDetail.jsx, src/renderer/src/components/plugins/PluginDetail.module.css, src/renderer/src/components/shaped-components/PluginButton.jsx
this will solve some points of the https://github.com/platformatic/meraki/issues/532
and resolve also https://github.com/platformatic/meraki/issues/386
=> 532 meraki review fixes after tests plugin name

src/renderer/src/components/applications/all/Row.module.css, src/renderer/src/components/applications/all/TopContent.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/applications/recent/Row.jsx, src/renderer/src/components/applications/recent/Row.module.css, src/renderer/src/components/applications/recent/TableRecent.jsx, src/renderer/src/components/applications/recent/TableRecent.module.css, src/renderer/src/components/applications/recent/TopContent.jsx
some small fixes from meraki-testing channel
=> Feature/small fixes UI 3

src/renderer/src/components/shaped-components/AddService.jsx, src/renderer/src/components/steps/GeneratingApplication.jsx, src/renderer/src/components/steps/PrepareFolder.jsx, src/renderer/src/components/steps/UpdatingApplication.jsx, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/steps/compose-application/GridElement.jsx, src/renderer/src/components/steps/compose-application/GridElement.module.css
fix: updating some points for the fixes on Compose Application and copy Logs
=> fix: small fixes ui 3

package-lock.json, package.json, src/renderer/src/components/plugins/PluginDetail.jsx, src/renderer/src/components/plugins/SelectPlugin.jsx, src/renderer/src/components/services/BundleFolderTree.jsx, src/renderer/src/components/services/NameService.jsx, src/renderer/src/components/shaped-components/AddPlugin.jsx, src/renderer/src/components/shaped-components/AddService.jsx, src/renderer/src/components/shaped-components/AddTemplate.jsx, src/renderer/src/components/shaped-components/ChangeTemplate.jsx, src/renderer/src/components/shaped-components/PlatformaticRuntimeButton.jsx, src/renderer/src/components/shaped-components/PluginButton.jsx, src/renderer/src/components/shaped-components/Routes.jsx, src/renderer/src/components/steps/ConfigureApplication.jsx, src/renderer/src/components/steps/CreateApplication.jsx, src/renderer/src/components/steps/EditConfigureApplication.jsx, src/renderer/src/components/steps/GeneratingApplication.jsx, src/renderer/src/components/steps/PrepareFolder.jsx, src/renderer/src/components/steps/UpdatingApplication.jsx, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/steps/configure-services/ConfigureServices.jsx, src/renderer/src/components/templates/SelectTemplate.jsx, src/renderer/src/components/templates/TemplateDetail.jsx, src/renderer/src/components/ui/EditableTitle.jsx, src/renderer/src/components/ui/NoResults.jsx, src/renderer/src/components/ui/Title.jsx
here a list of fixes that are requested on meraki testing
Create App Screen
A) Change the icon and reduce the size to 24px; ✅ 
B) Reduce to 8px; ✅ 
C) Reduce style from H2 to H3; ✅ 
D) Reduce size to 18pt to 16pt; ✅ 
E) Can we center this section in the page?
F) Can we add the arrow icon in the button "Next?" ✅ 
points on the Template/Plugin Modal:
A) Reduce icon size to 24px. Padding with the title to 8px; ✅ 
B) Reduce title style from H2 to H3; ✅ 
C) Reduce Text size to 16pt; ✅ 
In the "Create App Main view":
A) Reduce icon size to 24px. Padding with the title to 8px; ✅ 
B) Reduce App name from H3 to H2; ✅ 
C) Reduce icon size to 16px Padding with the title to 8px;; ✅ 
D) Reduce text size to 16pt; ✅ 
E) Reduce service title style Semibold 18pt; ✅ 
F) Reduce icon size …
=> fix: meraki testing ui changes part 4

src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/steps/compose-application/GridElement.jsx, src/renderer/src/components/steps/compose-application/GridElement.module.css, src/renderer/src/components/steps/compose-application/GridView.jsx, src/renderer/src/components/steps/compose-application/GridView.module.css
I fixed the behavior of the multiple templates.
=> handling bettere more than 4/5 template

package-lock.json, package.json, src/renderer/src/components/application/create/CreateApplicationFlow.jsx, src/renderer/src/components/application/edit/EditApplicationFlow.jsx, src/renderer/src/components/application/import/ImportApplicationFlow.jsx, src/renderer/src/components/application/overview/OverviewSection.jsx, src/renderer/src/components/application/overview/ServicesSection.jsx, src/renderer/src/components/applications/all/AllApplications.jsx, src/renderer/src/components/applications/all/TableAll.jsx, src/renderer/src/components/applications/recent/RecentApplications.jsx, src/renderer/src/components/plugins/Plugin.jsx, src/renderer/src/components/shaped-components/PluginButton.jsx, src/renderer/src/components/steps/GeneratingApplication.jsx, src/renderer/src/components/steps/compose-application/ComposeApplication.jsx, src/renderer/src/components/template-and-plugins/TemplateAndPluginTreeSelector.jsx, src/renderer/src/components/templates/Template.jsx
- added the prop for permanent modal
- added the logic for prevent same name for services
=> fix: adding props and service name updated

src/renderer/src/components/steps/configure-services/ConfigureServices.jsx
This will resolve https://github.com/platformatic/meraki/issues/217
below screenshot for the new handling
=> fix: updating regexp for validation

src/renderer/src/components/ApplicationContainer.jsx
Hi @marcopiraccini @mcollina 
this will solve the problem for not showing an Error when a user click on an Application that for some reason cannot be loaded.
Resolve https://github.com/platformatic/meraki/issues/602
=> fix: updating Application Container

src/renderer/src/components/Scalar.jsx
fix: updating Scalar custom css
=> Scalar update custom css

src/renderer/src/App.jsx
Resolve https://github.com/platformatic/meraki/issues/691
=> App error not handled

src/renderer/src/components/steps/EditConfigureApplication.jsx
this PR resolve https://github.com/platformatic/meraki/issues/725
=> Edit Application: Entrypoint removed should be blocked on Update App Step if no one is selected

build/entitlements.mac.plist, package.json
We are having this on mac builds: https://github.com/WiseLibs/better-sqlite3/issues/1110
=> mac-better-sqlite3-sign-fix 
